### PR TITLE
Michael - IntakeShooterSubsystem

### PR DESCRIPTION
**Pull request by themehdev**

### CODE REVIEW

**Review by blaze-developer — DISMISSED** [review]
When you wrote a target tracker placeholder class, could you isolate placeholders in your own class? Also, some of those things arent even what the target tracker would be calculating. 


P.S
also butch would not be happy with all your abstraction stuff, you should probably put your abstraction stuff onto a "michael-abstraction" branch and only merge the basic one onto main.

P.S P.S
in the org team1425 packages, you currently have util classes in a folder, so to get the xero timer class its org.team1425.XeroTimer.XeroTimer, that is pretty redundant, so intead i would reccoment putting utility classes in a folder maybe named, "util" or sorted in some other way.

P.S P.S P.S
i dont know if anyone else has a problem with this, but i would personally change org.Xero1425 to org.xerosw because it is more consistent with the general java development norms,  unless there is a reason *not* to change it

**Comment by themehdev** [comment]
for the last two:
I 100% agree

for the first one:
I still have no idea what the target tracker is supposed to be calculating; I thought it was calculating the shooter velocity, the up down position, and the tilt position and then giving that to the intake shooter subsystem through the TTShooter class that I made. 
However, if the target tracker is only supposed to be returning the distance the robot is from the base of the speaker, that is fine too. 
I will assume that it is the second option because you told me to change the first one.

**Comment by blaze-developer** [comment]
K, i can try to clarify today what it should be calculating and what needs to be calculated elsewhere. :3

**Comment by markkassab** [comment]
> for the last two: I 100% agree
> 
> for the first one: I still have no idea what the target tracker is supposed to be calculating; I thought it was calculating the shooter velocity, the up down position, and the tilt position and then giving that to the intake shooter subsystem through the TTShooter class that I made. However, if the target tracker is only supposed to be returning the distance the robot is from the base of the speaker, that is fine too. I will assume that it is the second option because you told me to change the first one.

@themehdev : The target tracker's responsibility is to indicate if a valid target exists, and if it does, information about its location such as its distance from a well-defined location on the robot (e.g., the center of the robot), and angle relative to the heading of the robot. It knows nothing about the IntakeShooter subsystem so not up to it to compute shooter velocity, tilt angle, etc. Those are more appropriate in the IntakeShooter subsystem.

**Comment by themehdev** [comment]
Everyone, 
I made those changes, and all the logic seems to be working. However, I am about 90% confident in my constants file, so I may need to tune that tomorrow. If you guys find any more bugs than tell me and I can fix them.

**Comment by blaze-developer** [comment]
Michael, I would advise that you **use** values like "inputs_.tiltPosition" in the code base instead of having getter methods on the IO implementations. Because that's like the entire point of inputs, that they can be replayed and referenced in the code. The inputs should be updated, and used for everything in the subsystem.

otherwise i think ur doing alright :>

**Comment by blaze-developer** [comment]
Some reading to hopefully understand the concept of replay better and to improve integration with the framework:

The new AdvantageKit documentation at [advantagekit.org](https://docs.advantagekit.org) is a bit more explanatory and nice.

Specifically I would read:

- [Their docs on IO interfaces](https://docs.advantagekit.org/recording-inputs/io-interfaces)
- [Their replay example #1](https://docs.advantagekit.org/what-is-advantagekit/example-output-logging)
- [Their replay example #2](https://docs.advantagekit.org/what-is-advantagekit/example-bug-fixes)
- [Their general overview if you need a general vision of the data flow.](https://docs.advantagekit.org/what-is-advantagekit/)

Just trying to be helpful! Hope this helps. Good day to you :3

**Review by blaze-developer — CHANGES_REQUESTED** [review]
As above

**Comment by blaze-developer** [comment]
I have branched off of this branch, and I have created a branch that has been updated to main, and has been nearly entirely fixed to work with AdvantageKit and log replay, with proper hardware abstraction. You will need to look at it and change a few things, and answer  a few questions I have  in the comments, it is on the branch "intakeshooter". I have made some changes and I have asked  some questions in the comments. So i would appreciate it if you took a look and modified it slightly to make it work how it should.

**Pull request closed without merging**
